apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  source:
    repoURL: https://github.com/wesleyfebarretos/gitops.git
    targetRevision: main
    path: platform/cert-manager

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
