apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-envoy-proxy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default

  source:
    repoURL: https://github.com/wesleyfebarretos/gitops.git
    targetRevision: main
    path: platform/envoy-proxy

  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
