apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-metrics-server
  namespace: kube-system
spec:
  project: default

  source:
    repoURL: https://github.com/wesleyfebarretos/gitops.git
    targetRevision: main
    path: platform/metrics-server

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
