apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: envoy-gateway
    repo: oci://docker.io/envoyproxy 
    version: v1.8.0
    releaseName: gateway-helm
    namespace: envoy-gateway-system
    valuesFile: values.yaml