apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: golang-api
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/wesleyfebarretos/gitops.git
        revision: main
        files:
          - path: clients/*/*
  template:
    metadata:
      name: "{{ .namespace }}-golang-api"
      labels:
        app.kubernetes.io/name: golang-api
        client: "{{ index .path.segments 1 }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/wesleyfebarretos/gitops.git
        targetRevision: main
        path: helm/charts/golang-api
        helm:
          releaseName: "{{ .namespace }}"
          valueFiles:
            - ../../../{{ .path.path }}/{{ .path.filename }}
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
