namespace: acme3-prod

nameOverride: acme3-prod
fullnameOverride: acme3-prod

image:
  repository: golang-api
  tag: 568a59b 
  pullPolicy: IfNotPresent

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 100
  targetCPUUtilizationPercentage: 65
  targetMemoryUtilizationPercentage: 60