namespace: acme2-prod

nameOverride: acme2-prod
fullnameOverride: acme2-prod

image:
  repository: acme2-prod
  tag: 568a59b 
  pullPolicy: IfNotPresent

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 100
  targetCPUUtilizationPercentage: 65
  targetMemoryUtilizationPercentage: 60