namespace: acme-prod

nameOverride: acme-prod
fullnameOverride: acme-prod

image:
  repository: golang-api
  tag: 568a59b 
  pullPolicy: Never

autoscaling:
  enabled: true
  minReplicas: 20
  maxReplicas: 100
  targetCPUUtilizationPercentage: 65
  targetMemoryUtilizationPercentage: 60